---
AWSTemplateFormatVersion: '2010-09-09'
Description: Demo DB Cluster Endpoint Provider
Parameters:
  VPC:
    Description: imported variable
    Type: String
  Subnets:
    Description: List of subnets to create the database in
    Type: List<AWS::EC2::Subnet::Id>
Resources:
  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBClusterIdentifier: !Ref AWS::StackName
      Engine: aurora-postgresql
      EngineVersion: '10.7'
      DatabaseName: aurora
      Port: 5432
      MasterUsername: root
      MasterUserPassword: !Select
        - 2
        - !Split [ '/', !Ref 'AWS::StackId']
      DBSubnetGroupName: !Ref 'DBSubnetGroup'
      VpcSecurityGroupIds:
        - !Ref 'ClusterSecurityGroup'
      DBClusterParameterGroupName: !Ref 'RDSDBClusterParameterGroup'

  AuroraDBFirstInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties:
      DBInstanceClass: db.t3.medium
      DBClusterIdentifier: !Ref 'AuroraDBCluster'
      Engine: aurora-postgresql
      EngineVersion: '10.7'
      DBParameterGroupName: !Ref 'DBParamGroup'
      AutoMinorVersionUpgrade: false
      DBSubnetGroupName: !Ref 'DBSubnetGroup'
      PubliclyAccessible: false
      EnablePerformanceInsights: true

  AuroraDBSecondInstance:
    Type: AWS::RDS::DBInstance
    DependsOn:
      - AuroraDBFirstInstance
    Properties:
      CopyTagsToSnapshot: true
      DBInstanceClass: db.t3.medium
      DBClusterIdentifier: !Ref 'AuroraDBCluster'
      Engine: aurora-postgresql
      EngineVersion: '10.7'
      DBParameterGroupName: !Ref 'DBParamGroup'
      AutoMinorVersionUpgrade: true
      DBSubnetGroupName: !Ref 'DBSubnetGroup'
      PubliclyAccessible: false
      EnablePerformanceInsights: true

  RDSDBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: aurora-postgresql
      Family: aurora-postgresql10
      Parameters:
        rds.force_ssl: 1

  DBParamGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: aurora-postgresql
      Family: aurora-postgresql10
      Parameters:
        shared_preload_libraries: auto_explain,pg_stat_statements,pg_hint_plan,pgaudit
        log_statement: ddl
        log_connections: '1'
        log_disconnections: '1'
        log_lock_waits: '1'
        log_min_duration_statement: '5000'
        auto_explain.log_min_duration: '5000'
        auto_explain.log_verbose: '1'
        log_rotation_age: '1440'
        log_rotation_size: '102400'
        rds.log_retention_period: '10080'
        random_page_cost: '1'
        track_activity_query_size: '16384'
        idle_in_transaction_session_timeout: '7200000'
        statement_timeout: '7200000'
        search_path: '"$user",public'

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Ref 'AWS::StackName'
      SubnetIds: !Ref 'Subnets'
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  ClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: postgresql access
      VpcId: !Ref 'VPC'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          Description: www access

          CidrIp: 0.0.0.0/0
      SecurityGroupEgress: []
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  ClusterSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt 'ClusterSecurityGroup.GroupId'
      IpProtocol: '-1'
      SourceSecurityGroupId: !Ref 'ClusterSecurityGroup'
      Description: Self Reference

  ReaderEndpoint:
    Type: Custom::DBClusterEndpoint
    Properties:
      DBClusterIdentifier: !Ref 'AuroraDBCluster'
      DBClusterEndpointIdentifier: 'readers'
      EndpointType: 'READER'
      StaticMembers:
        - !Ref AuroraDBFirstInstance
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-db-cluster-endpoint-provider'

Outputs:
  Endpoint:
    Value: !GetAtt ReaderEndpoint.Endpoint
  EndpointArn:
    Value: !GetAtt ReaderEndpoint.Arn